model_path: E:\PythonProjects\RapidOCR\python\onnxruntime_infer\models\PPOCRv3\ch_PP-OCRv3_rec_infer.onnx

rec_img_shape: [3, 48, 320]
rec_batch_num: 6
keys_path: E:\PythonProjects\RapidOCR\python\onnxruntime_infer\rec_dict\ppocr_keys_v1.txt
