model_path: E:\PythonProjects\RapidOCR\python\onnxruntime_infer\models\ch_ppocr_server_v2.0_rec_infer.onnx

rec_img_shape: [3, 32, 320]
rec_batch_num: 6
keys_path: E:\PythonProjects\RapidOCR\python\onnxruntime_infer\rec_dict\ppocr_keys_v1.txt
