name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  sync:
      runs-on: ubuntu-latest
      steps:
        - uses: wearerequired/git-mirror-action@master
          env:
            SSH_PRIVATE_KEY: ${{ secrets.GEN_PYTHON_SDK }}
          with:
            source-repo: "git@github.com:RapidAI/RapidOCR.git"
            destination-repo: "git@gitee.com:RapidAI/RapidOCR.git"
