name: Test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    #  echo "action_state=%date:~0,4%%date:~5,2%%date:~8,2%0%time:~1,1%%time:~3,2%%time:~6,2%" >> %GITHUB_ENV%
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=%date:~0,4%%date:~5,2%%date:~8,2%0%time:~1,1%%time:~3,2%%time:~6,2%" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append  
         
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_X
          utcOffset: "+08:00"
      - name: Use the value
        id: step_two
        run: |
             echo "${{ steps.current-time.outputs.time }}" # This will output 'yellow'
      
